
2018-11-22 09:09:53,281 - error - INFO - basic_log : 19 - Traceback (most recent call last):
  File "/home/work/erp/erp_sites/views/person.py", line 159, in personDelete
    identifier = reuqest.GET['identifier']
NameError: global name 'reuqest' is not defined

2018-11-22 09:25:05,929 - error - INFO - basic_log : 19 - Traceback (most recent call last):
  File "/home/work/erp/erp_sites/views/basicOperat.py", line 215, in basicSelect
    table_name = request.GET['table_name']
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.13-py2.7.egg/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'table_name'"

